### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by pisaiah** [IsaiahPatton/vpaint#1]
# vPaint Todo List

## Format support
- [x] PNG support
- [x] JPEG support
- [ ] WEBP support
- [ ] QOI support
- [x] Saving / Loading
- [x] Saving / Loading on Wasm.

## Zoom support
- [x] Ability to zoom image (25% - 800%+)
- [x] Draw canvas without image blending
- [ ] Zoom slider, instead of buttons.

## Editing
- [ ] Layer support
	- [ ] movable layers
- [ ] Brushes
	- [x] Pencil Brush
	- [x] Calligraphy Brush (Right Facing) 
	- [x] Calligraphy Brush (Left Facing)
	- [x] Use line algorithm for drawing. [.](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm?scrlybrkr=b3b966a6)
    - [x] Spray-can Brush
	- [x] Paint bucket
	- [ ] Eraser
- [ ] Shapes
	- [x] Rectangle
	- [x] Square
	- [x] Line
	- [ ] Triangle
	- [x] Circle
	- [ ] Rounded Rectangle
- [ ] Colors
    - [x] Basic color table selection
    - [x] RGB color selection
    - [x] Primary / Secondary Colors.

## Canvas
- [ ] Resizable
- [ ] Resizable (by drag)
- [ ] Skew
- [ ] Rotate

**Comment by pisaiah** [comment]
Color picker:

![image](https://user-images.githubusercontent.com/16439221/156215920-66a416c8-1782-436e-81ba-177f0bc613e4.png)

![image](https://user-images.githubusercontent.com/16439221/156216034-7d0a8abf-fa36-4d46-a199-96acba00789c.png)
